<?php echo $this->doctype() ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <?php
    $this->commonIncludes();
    $this->headLink()->appendStylesheet($this->baseUrl('css/tmpl-backend.css'));

    echo $this->headTitle();
    echo $this->headLink();
    ?>

    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <link rel="shortcut icon" href="<?php echo $this->baseUrl('favicon.ico') ?>">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
</head>

<body>

<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container-fluid">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <a class="brand" href="#">ZF Template</a>

            <div class="nav-collapse">
                <ul class="nav">
                    <li class="active"><a href="#">Admin Zone</a></li>
                </ul>
                <p class="navbar-text pull-right">
                    <?php echo $this->loggedInUser(); ?>
                </p>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid">
    <?php echo $this->messages(); ?>
    <div class="row-fluid">
        <div class="<?php echo $this->layout()->mainSpan ?>">
            <?php echo $this->layout()->content; ?>
        </div>
    </div>

    <hr>
    <footer>
        <p>&copy; Company 2012</p>
    </footer>
</div>

<script src="<?php echo $this->baseUrl('js/jquery-1.7.2.min.js') ?>"></script>
<script src="<?php echo $this->baseUrl('js/bootstrap.js') ?>"></script>
</body>
</html>
